version: "3"
services:
  app:
    image: webdevops/php-nginx-dev:7.2
    container_name: [named your container]
    networks:
      - [put your docker's network name]
    volumes:
      - .:/app
      - ./docker_config/php.ini:/opt/docker/etc/php/php.ini
    environment:
      - PHP_DEBUGGER=xdebug
      - PHP_DISPLAY_ERRORS=1
      - PHP_DATE_TIMEZONE=Asia/Ho_Chi_Minh
      - WEB_DOCUMENT_ROOT=/app/public
    labels:
      - traefik.enable=true
      - traefik.backend=[named backed name]
      - traefik.frontend.rule=Host:[put your domain name]
      - traefik.docker.network=[put your docker's network name]
      - traefik.port=80
  nodejs:
    image: node:8
    container_name: [named your container]
    stdin_open: true
    networks:
      - [put your docker's network name]
    volumes:
      - .:/app
  db:
    image: mysql:5.7.24
    container_name: [named your container]
    networks:
      - [put your docker's network name]
    command: mysqld --user=root --verbose
    volumes:
      - ./docker_config/script.sql:/tmp/script.sql
      - ./docker_config/import.sh:/tmp/import.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "databasename"
      MYSQL_USER: [whatever you want]
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: [named your container]
      environment:
        - PMA_ARBITRARY=1
      restart: always
      links:
        - "db: db"
      ports:
        - 9090:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: db
      networks:
        - proxy
  traefik:
    image: traefik
    container_name: [named your container]
    command:
      - --api
      - --docker
      - --docker.exposedbydefault=false
    restart: always
    ports:
      - 80:80
      - 8080:8080
    networks:
      - [put your docker's network name]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  proxy:
    external: true
